// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

import 'package:flutter_surrealdb/utils.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'options.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'engine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_connection`, `conn`, `create_missing_table`, `escape_surreal_ident`, `is_missing_table`, `missing_table_fallback`, `release`, `retry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SurrealFlutterEngine>>
abstract class SurrealFlutterEngine implements RustOpaqueInterface {
  /// Releases this engine handle: its session is removed (killing the live
  /// queries created through it) and, for shared connections, its lease is
  /// dropped. When the last handle of a shared connection is released, the
  /// connection is deregistered and its datastore, together with the file
  /// lock, is dropped.
  Future<void> close();

  Future<void> closeSession({required List<int> id});

  /// Connects to a SurrealDB instance.
  ///
  /// Without [share_tag] the returned handle owns a private connection.
  /// With [share_tag] the handle attaches to the process-wide connection
  /// registered under that tag, creating it if needed; this is what allows
  /// other isolates to use the same database even though its file is locked
  /// by the first connection. Attaching is rejected when the tag is already
  /// registered with a different endpoint or different options.
  static Future<SurrealFlutterEngine> connect(
          {required String endpoint, Options? opts, String? shareTag}) =>
      RustLib.instance.api.crateApiEngineSurrealFlutterEngineConnect(
          endpoint: endpoint, opts: opts, shareTag: shareTag);

  Future<Uint8List> createSession();

  Future<Uint8List> execute(
      {required Method method, required List<int> params, Uint8List? session});

  /// Streams the database export to [sink] in chunks instead of buffering
  /// the whole export in memory. Cancelling the Dart-side stream aborts the
  /// export.
  Stream<Uint8List> exportStream({Config? config, Uint8List? session});

  Future<Uint8List> forkSession({required List<int> id});

  Future<void> import_({required String input, Uint8List? session});

  Stream<DBNotification> notifications();

  static String version() =>
      RustLib.instance.api.crateApiEngineSurrealFlutterEngineVersion();
}

enum Action {
  create,
  update,
  delete,
  unkown,
  killed,
  error,
  ;
}

class Config {
  final bool users;
  final bool accesses;
  final bool params;
  final bool functions;
  final bool analyzers;
  final bool apis;
  final bool buckets;
  final bool modules;
  final bool configs;
  final TableConfig tables;
  final bool versions;
  final bool records;
  final bool sequences;

  const Config({
    required this.users,
    required this.accesses,
    required this.params,
    required this.functions,
    required this.analyzers,
    required this.apis,
    required this.buckets,
    required this.modules,
    required this.configs,
    required this.tables,
    required this.versions,
    required this.records,
    required this.sequences,
  });

  @override
  int get hashCode =>
      users.hashCode ^
      accesses.hashCode ^
      params.hashCode ^
      functions.hashCode ^
      analyzers.hashCode ^
      apis.hashCode ^
      buckets.hashCode ^
      modules.hashCode ^
      configs.hashCode ^
      tables.hashCode ^
      versions.hashCode ^
      records.hashCode ^
      sequences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          users == other.users &&
          accesses == other.accesses &&
          params == other.params &&
          functions == other.functions &&
          analyzers == other.analyzers &&
          apis == other.apis &&
          buckets == other.buckets &&
          modules == other.modules &&
          configs == other.configs &&
          tables == other.tables &&
          versions == other.versions &&
          records == other.records &&
          sequences == other.sequences;
}

class DBNotification {
  final Uint8List id;
  final Action action;
  final Uint8List record;
  final Uint8List result;

  const DBNotification({
    required this.id,
    required this.action,
    required this.record,
    required this.result,
  });

  @override
  int get hashCode =>
      id.hashCode ^ action.hashCode ^ record.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DBNotification &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          record == other.record &&
          result == other.result;
}

class ExcludedTables {
  final List<String> exclude;

  const ExcludedTables({
    required this.exclude,
  });

  @override
  int get hashCode => exclude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExcludedTables &&
          runtimeType == other.runtimeType &&
          exclude == other.exclude;
}

enum Method {
  unknown,
  ping,
  info,
  use,
  signup,
  signin,
  authenticate,
  refresh,
  invalidate,
  revoke,
  reset,
  kill,
  live,
  set_,
  unset,
  select,
  insert,
  create,
  upsert,
  update,
  merge,
  patch,
  delete,
  version,
  query,
  gql,
  graphql,
  relate,
  run,
  insertRelation,
  attach,
  sessions,
  detach,
  begin,
  commit,
  cancel,
  ;
}

@freezed
sealed class TableConfig with _$TableConfig {
  const TableConfig._();

  const factory TableConfig.all() = TableConfig_All;
  const factory TableConfig.none() = TableConfig_None;
  const factory TableConfig.some(
    List<String> field0,
  ) = TableConfig_Some;
  const factory TableConfig.exclude(
    ExcludedTables field0,
  ) = TableConfig_Exclude;
}
