// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import 'package:flutter_surrealdb/utils.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'options.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'engine.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SurrealFlutterEngine>>
abstract class SurrealFlutterEngine implements RustOpaqueInterface {
  Future<void> closeSession({required List<int> id});

  static Future<SurrealFlutterEngine> connect(
          {required String endpoint, Options? opts}) =>
      RustLib.instance.api.crateApiEngineSurrealFlutterEngineConnect(
          endpoint: endpoint, opts: opts);

  Future<Uint8List> createSession();

  Future<Uint8List> execute(
      {required Method method, required List<int> params, Uint8List? session});

  Future<String> export_({Config? config, Uint8List? session});

  Future<Uint8List> forkSession({required List<int> id});

  Future<void> import_({required String input, Uint8List? session});

  Stream<DBNotification> notifications();

  static String version() =>
      RustLib.instance.api.crateApiEngineSurrealFlutterEngineVersion();
}

enum Action {
  create,
  update,
  delete,
  unkown,
  ;
}

class Config {
  final bool users;
  final bool accesses;
  final bool params;
  final bool functions;
  final bool analyzers;
  final TableConfig tables;
  final bool versions;
  final bool records;
  final bool sequences;

  const Config({
    required this.users,
    required this.accesses,
    required this.params,
    required this.functions,
    required this.analyzers,
    required this.tables,
    required this.versions,
    required this.records,
    required this.sequences,
  });

  @override
  int get hashCode =>
      users.hashCode ^
      accesses.hashCode ^
      params.hashCode ^
      functions.hashCode ^
      analyzers.hashCode ^
      tables.hashCode ^
      versions.hashCode ^
      records.hashCode ^
      sequences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          users == other.users &&
          accesses == other.accesses &&
          params == other.params &&
          functions == other.functions &&
          analyzers == other.analyzers &&
          tables == other.tables &&
          versions == other.versions &&
          records == other.records &&
          sequences == other.sequences;
}

class DBNotification {
  final Uint8List id;
  final Action action;
  final Uint8List record;
  final Uint8List result;

  const DBNotification({
    required this.id,
    required this.action,
    required this.record,
    required this.result,
  });

  @override
  int get hashCode =>
      id.hashCode ^ action.hashCode ^ record.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DBNotification &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          record == other.record &&
          result == other.result;
}

enum Method {
  unknown,
  ping,
  info,
  use,
  signup,
  signin,
  authenticate,
  invalidate,
  reset,
  kill,
  live,
  set_,
  unset,
  select,
  insert,
  create,
  upsert,
  update,
  merge,
  patch,
  delete,
  version,
  query,
  relate,
  run,
  insertRelation,
  ;
}

@freezed
sealed class TableConfig with _$TableConfig {
  const TableConfig._();

  const factory TableConfig.all() = TableConfig_All;
  const factory TableConfig.none() = TableConfig_None;
  const factory TableConfig.some(
    List<String> field0,
  ) = TableConfig_Some;
}
