// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import 'package:flutter_surrealdb/utils.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'options.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SurrealFlutterEngine>>
abstract class SurrealFlutterEngine implements RustOpaqueInterface {
  static Future<SurrealFlutterEngine> connect(
          {required String endpoint, Options? opts}) =>
      RustLib.instance.api.crateApiEngineSurrealFlutterEngineConnect(
          endpoint: endpoint, opts: opts);

  Future<Uint8List> execute({required List<int> data});

  Future<String> export_({Uint8List? config});

  Future<void> import_({required String input});

  Stream<DBNotification> notifications();

  static Future<String> version() =>
      RustLib.instance.api.crateApiEngineSurrealFlutterEngineVersion();
}

enum Action {
  create,
  update,
  delete,
  unkown,
  ;
}

class DBNotification {
  final Uint8List id;
  final Action action;
  final Uint8List record;
  final Uint8List result;

  const DBNotification({
    required this.id,
    required this.action,
    required this.record,
    required this.result,
  });

  @override
  int get hashCode =>
      id.hashCode ^ action.hashCode ^ record.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DBNotification &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          record == other.record &&
          result == other.result;
}
